name: "S3 Test Server"
description: "Setup an S3 server for testing gatsby-source-s3"

runs:
  using: "composite" # Mandatory parameter
  steps:
    - name: Setup minio
      run: |
        docker run -d -p 9000:9001 --name minio \
          -e "MINIO_ACCESS_KEY=minioadmin" \
          -e "MINIO_SECRET_KEY=minioadmin" \
          -v ${{ GITHUB_WORKSPACE }}/integration-tests/source-s3/test-data/:/data \
          minio/minio server /data
